services:
  xray-vpn:
    image: ghcr.io/xtls/xray-core
    container_name: "core"
    ports:
      - "443:443"
    volumes:
      - ./configs/config.json:/etc/xray/config.json
    restart: unless-stopped

  bot:
    image: "telegram-bot"
    build:
      context: .
      dockerfile: ./build/bot/Dockerfile
    volumes:
      - ./configs/config.json:/app/configs/config.json
      - ./configs/config.yaml:/app/configs/config.yaml
      - ./db:/app/db
      - /var/run/docker.sock:/var/run/docker.sock
